Update metrics
OpenTermsArchive/opentermsarchive.org pull request #310
Opened 2024-03-22 14:46 UTC by Ndpnt

2024-03-22 16:04 UTC, MattiSG requested changes
The addition of new contributors, along with images and website, have to be confirmed with said contributors.

2024-03-22 16:04 UTC, MattiSG commented on data/stats.yaml
> +  collections: 8
> If it's easy to just get the count from the data, we might as well do that here 😇

2024-03-22 16:04 UTC, MattiSG commented on data/stats.yaml
> +  terms: 1429
These are currently hardcoded with a `+`, so either remove the `+` from the template or round it down.
```suggestion
  services: 700
  terms: 1400
```

2024-03-22 16:04 UTC, MattiSG commented on data/contributors.json
> +    "Emmanuel Haguet": "https://github.com/Manu1400",
Which contribution are we mentioning?

2024-03-22 16:04 UTC, MattiSG commented on data/contributors.json
> +    "Brice BAI": "https://github.com/bricebai1",
```suggestion
    "Brice Bai": "https://github.com/bricebai1",
```

2024-03-22 16:04 UTC, MattiSG commented on data/contributors.json
> +    "omjdi": "https://github.com/omjdi"
Which contribution are we mentioning?

2024-03-22 16:06 UTC, Ndpnt commented
> The addition of new contributors, along with images and website, have to be confirmed with said contributors.

OK, that's what I was wondering.

2024-03-22 16:07 UTC, Ndpnt commented on data/stats.yaml
> +  collections: 8
I do not understand what you mean here

2024-03-25 10:41 UTC, clementbiron approved these changes

2024-03-26 12:51 UTC, MattiSG approved these changes
👍 🚀

2024-03-26 13:06 UTC, merged