Reference EU Contracts database & P2B impact assessment as reuses
OpenTermsArchive/opentermsarchive.org pull request #311
Opened 2024-03-25 09:21 UTC by clementbiron

2024-03-25 10:45 UTC, Ndpnt commented on content/impact/compliance.fr.md
> +- En novembre 2022, la Commission européenne a [publié une rapport](https://op.europa.eu/en/publication-detail/-/publication/d6a287b5-5116-11ee-9220-01aa75ed71a1/language-en/) utilisant Open Terms Ar
```suggestion
- En novembre 2022, la Commission européenne a [publié une rapport](https://op.europa.eu/en/publication-detail/-/publication/d6a287b5-5116-11ee-9220-01aa75ed71a1/language-en/) utilisant Open Terms Archive pour faire une [évaluation à grande échelle](https://ppmi.lt/news-insights/ppmi-has-completed-early-evaluation-p2b-regulation) de la conformité au règlement P2B.
```

2024-03-25 10:45 UTC, Ndpnt commented on content/impact/compliance.fr.md
>  - En mars 2023, l'essai de conformité P2B a suffisamment démontré la valeur d'Open Terms Archive pour que la Commission européenne [l'adopte](https://github.com/OpenTermsArchive/engine/issues/1001) c
```suggestion
- En mars 2023, l'essai de conformité P2B a suffisamment démontré la valeur d'Open Terms Archive pour que la Commission européenne [l'adopte](https://github.com/OpenTermsArchive/engine/issues/1001) comme outil fondamental pour sa nouvelle équipe interne d'application du DSA au sein de son Centre commun de recherche.
```

2024-03-26 13:01 UTC, MattiSG requested changes

2024-03-26 13:32 UTC, clementbiron commented on data/reuses/digital-services-terms-and-conditions-database.yaml
> +  fr: Base de données issue d'une initiative de la Commission européenne qui présente les conditions générales des services numériques, en mettant l'accent sur les plateformes en ligne telles que les
I haven't found anything better 🤔

2024-03-27 13:22 UTC, MattiSG requested changes

2024-03-27 13:22 UTC, MattiSG commented on content/impact/compliance.md
> +- In November 2022, the European Commission has [finalised a report](https://op.europa.eu/en/publication-detail/-/publication/d6a287b5-5116-11ee-9220-01aa75ed71a1/language-en/) using the Open Terms A
Please follow our copywriting guidelines.

```suggestion
- In November 2022, the European Commission has [finalised a report](https://op.europa.eu/en/publication-detail/-/publication/d6a287b5-5116-11ee-9220-01aa75ed71a1/language-en/) using Open Terms Archive to conduct a large-scale [assessment](https://ppmi.lt/news-insights/ppmi-has-completed-early-evaluation-p2b-regulation) of compliance with the [P2B Regulation](https://eur-lex.europa.eu/eli/reg/2019/1150/oj).
```

2024-03-27 13:22 UTC, MattiSG commented on data/reuses/p2b-impact-assessment.yaml
> +  en: P2B impact assessment
```suggestion
  en: P2B regulation impact assessment
```

2024-03-27 13:22 UTC, MattiSG commented on data/reuses/p2b-impact-assessment.yaml
> +  fr: Évaluation de l'impact du réglement européen P2B
```suggestion
  fr: Étude d'impact du règlement P2B
```

2024-03-27 13:22 UTC, MattiSG commented on data/reuses/p2b-impact-assessment.yaml
> +  fr: Étude sur l'évaluation du règlement (UE) 2019/1150 relatif à la promotion de l'équité et de la transparence pour les entreprises utilisatrices de services d'intermédiation en ligne (le règlemen
```suggestion
  en: Large-scale assessment of compliance with the Regulation (EU) 2019/1150 on promoting fairness and transparency for business users of online intermediation services (“P2B Regulation”).
  fr: Évaluation à grande échelle de conformité au règlement (UE) 2019/1150 relatif à la promotion de l'équité et de la transparence pour les entreprises utilisatrices de services d'intermédiation en ligne (« règlement P2B »).
```

2024-03-27 13:26 UTC, MattiSG commented
Can we please make the illustrations full width, like the others? 🙂 

<img width="1260" alt="image" src="https://github.com/OpenTermsArchive/opentermsarchive.org/assets/222463/73af6eb0-9d1b-497f-91a2-712b9257c8a4">

2024-03-28 14:09 UTC, Ndpnt approved these changes

2024-03-28 14:15 UTC, merged

2024-03-29 04:23 UTC, MattiSG commented
> Nicolas did it
I don't understand 😅